[project]
name = "mokai"
cpp_version = "c++23"
include_dirs = ["src"]

[property_group.engine_defines]
defines = ['MOKAI_TEMPLATE_DIR="/home/k/Documents/mokai/src/templates"']

[target.MOKAI]
type = "static_library"
sources = [
    "src/config/**/*.cpp", 
    "src/graph/**/*.cpp", 
    "src/utils/**/*.cpp",
    "src/cli/**/*.cpp",
    "src/log/**/*.cpp"
]

[target.mokai]
type = "executable"
sources = ["src/entery.cpp"]
properties = ["@engine_defines"]
depends_on = ["MOKAI"]
